# Generated by Django 3.0.7 on 2020-09-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200906_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creater',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
