# Generated by Django 3.0.7 on 2020-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chatrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrel',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
