# Generated by Django 3.0.7 on 2020-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userlastsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlastsession',
            name='status',
            field=models.CharField(choices=[(1, 'onLine'), (2, 'offLine')], default='offline', max_length=200),
        ),
    ]
