# Generated by Django 3.0.7 on 2020-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201211_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlastsession',
            name='status',
            field=models.IntegerField(choices=[(1, 'onLine'), (2, 'offLine')], default='offline', max_length=200),
        ),
    ]
