# Generated by Django 3.0.7 on 2020-12-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20201211_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlastsession',
            name='status',
            field=models.IntegerField(choices=[(1, 'onLine'), (0, 'offLine')], default=0),
        ),
        migrations.AlterField(
            model_name='userlastsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_online_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
