# Generated by Django 3.0.7 on 2020-07-28 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artical', '0014_auto_20200724_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=400)),
                ('profile_image', models.ImageField(blank=True, upload_to='')),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('creater', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
