# Generated by Django 3.0.7 on 2020-09-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0018_auto_20200902_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical_m',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artical.Category'),
        ),
    ]
