# Generated by Django 3.0.7 on 2020-09-09 15:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('artical', '0020_auto_20200905_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical_m',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
