# Generated by Django 3.0.7 on 2020-11-29 06:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0021_artical_m_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical_m',
            name='content',
            field=tinymce.models.HTMLField(default='dev'),
            preserve_default=False,
        ),
    ]
